// <auto-generated />
using System;
using AgentOrchestrator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentOrchestrator.Infrastructure.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    [Migration("20260626203410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentOrchestrator.Domain.Aggregates.IncidentAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("IncidentDescription")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("IncidentTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("incident_analyses", (string)null);
                });

            modelBuilder.Entity("AgentOrchestrator.Domain.Aggregates.IncidentAnalysis", b =>
                {
                    b.OwnsOne("AgentOrchestrator.Domain.ValueObjects.AnalysisResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("IncidentAnalysisId");

                            b1.Property<double?>("Confidence");

                            b1.Property<string>("Reasoning")
                                .IsRequired();

                            b1.Property<string>("SuggestedCategory")
                                .IsRequired();

                            b1.Property<string>("SuggestedPriority")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("SuggestedSteps")
                                .IsRequired();

                            b1.HasKey("IncidentAnalysisId");

                            b1.ToTable("incident_analyses");

                            b1
                                .ToJson("result")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IncidentAnalysisId");
                        });

                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
