// <auto-generated />
using System;
using AgentOrchestrator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentOrchestrator.Infrastructure.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    partial class AgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentOrchestrator.Domain.Aggregates.IncidentAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("IncidentDescription")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("IncidentTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("incident_analyses", (string)null);
                });

            modelBuilder.Entity("BuildingBlocks.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("AgentOrchestrator.Domain.Aggregates.IncidentAnalysis", b =>
                {
                    b.OwnsOne("AgentOrchestrator.Domain.ValueObjects.AnalysisResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("IncidentAnalysisId");

                            b1.Property<double?>("Confidence");

                            b1.Property<string>("Reasoning")
                                .IsRequired();

                            b1.Property<string>("SuggestedCategory")
                                .IsRequired();

                            b1.Property<string>("SuggestedPriority")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("SuggestedSteps")
                                .IsRequired();

                            b1.HasKey("IncidentAnalysisId");

                            b1.ToTable("incident_analyses");

                            b1
                                .ToJson("result")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IncidentAnalysisId");

                            b1.OwnsOne("AgentOrchestrator.Domain.ValueObjects.AnalysisMetadata", "Metadata", b2 =>
                                {
                                    b2.Property<Guid>("AnalysisResultIncidentAnalysisId");

                                    b2.Property<long>("EndToEndDurationMs");

                                    b2.Property<int>("InputTokens");

                                    b2.Property<string>("ModelName")
                                        .IsRequired();

                                    b2.Property<int>("OutputTokens");

                                    b2.HasKey("AnalysisResultIncidentAnalysisId");

                                    b2.ToTable("incident_analyses");

                                    b2.WithOwner()
                                        .HasForeignKey("AnalysisResultIncidentAnalysisId");
                                });

                            b1.Navigation("Metadata");
                        });

                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
